### ISSUE TITLE
404 error - .../dist/dist/modules/ng2-expansion-panels.module.js

### ISSUE THREAD

**Issue by randyangeles** [Gbuomprisco/ng2-expansion-panels#1]
Hi,

Getting the 404 error above when I try to run a project using the SystemJS loader.

It looks like the ng2-expansion-panels.module.js file isn't getting included in the node_modules folder?

Wondering if this is an issue or am I missing something?

**System-config.js setup**
 (we copy all .js files from node_modules to wwwroot/lib using a gulp task)
```
map: {
    //...
    'ng2-expansion-panels': 'lib/ng2-expansion-panels'
}
packages: {
    //...
    'ng2-expansion-panels': {
        main: 'dist/index.js',
        defaultExtension: 'js',
     }
}
```

**Workaround**
I can the project to run by replacing index.js with the following:

```
"use strict";
var ng2_expansion_panels_module_1 = require('./ng2-expansion-panels.bundle');
exports.ExpansionPanelsModule = ng2_expansion_panels_module_1.ExpansionPanelsModule;
//# sourceMappingURL=index.js.map
```

**Comment by Gbuomprisco** [comment]
Hi @randyangeles,

can you try replacing index.js with ng2-expansion-panels.bundle.js?

**Comment by randyangeles** [comment]
That worked! Thanks @Gbuomprisco! Closing this issue.
