### ISSUE TITLE
25% left margin of content

### ISSUE THREAD

**Issue by mjawulski** [Gbuomprisco/ng2-expansion-panels#2]
Hi!
Is there any way I can disable 25% left margin of expansion-panel__content class?
Maybe value of margin should be configurable?

**Comment by Gbuomprisco** [comment]
Hi @mjawulski,

it is not possible at this time. It's sort of how the material specs defines, so I didn't think it would have needed configuration. Maybe you could use component inheritance to define your own style. I will have to upgrade the Angular version and add this to the readme :)
