### ISSUE TITLE
Cannot find module ng2-expansion-panels

### ISSUE THREAD

**Issue by wesleyanemam** [Gbuomprisco/ng2-expansion-panels#6]
It seems that the npm package is 'unstable'. Webpack can't find the main file from the node_modules/ng2-expansion-panels even though it is present.

I checked the package.json file and the main file is set to ./dist/ng2-expansion-panels.bundle.js

I've tried to rename ng2-expansion-panels.bundle.js to index.js and move it to node_modules/ng2-expansion-panels and still got the error.

Any idea why webpack is unable to find ?

Found that a similar issue is also happening on the build
https://travis-ci.org/Gbuomprisco/ng2-expansion-panels/builds/208121019

Additional info:

node -v
v7.2.1

npm -v
3.10.10

```shell
$ cat node_modules/ng2-expansion-panels/package.json  | grep main
  "main": "./dist/ng2-expansion-panels.bundle.js" 

$ cat node_modules/ng2-expansion-panels/package.json  | grep version
  "version": "0.0.3"

$ ls -1 node_modules/ng2-expansion-panels/**
node_modules/ng2-expansion-panels/README.md
node_modules/ng2-expansion-panels/package.json

node_modules/ng2-expansion-panels/dist:
modules
ng2-expansion-panels.bundle.js
ng2-expansion-panels.map
vendor.bundle.js
vendor.map

```

**Comment by Gbuomprisco** [comment]
Hi @wesleyanemam,

could you try the new version? thanks

**Comment by Gbuomprisco** [comment]
Should be related to https://github.com/Gbuomprisco/ng2-expansion-panels/issues/5#issuecomment-287651345 :) reopen if still valid please
