### ISSUE TITLE
Make it horizontal?

### ISSUE THREAD

**Issue by hzitoun** [Gbuomprisco/ng2-expansion-panels#9]

**Comment by Gbuomprisco** [comment]
Sorry - I don't think the material guidelines provide such a thing. Also, it would be a sort of tabs component?

**Comment by hzitoun** [comment]
A sort of sidenav (https://material.angular.io/components/component/sidenav) with the same collapse/expand operation

**Comment by Gbuomprisco** [comment]
I am fairly sure angular material has one :) (seems still a different component imho)

EDIT: thought it was the style guidelines link. Sorry but I think it would have to be done in a different component.

**Comment by hzitoun** [comment]
Why it have to be done in a different component while it remains an expansion panel exactly as what you've done with the only difference of the orientation?
